# data parameters
dataset_name: CELEBA
data_with_subfolder: False

data_path: D:/db/celebaHQ/CelebAMask-HQ/CelebA-HQ-img   # celeba
#data_path: /home/cardongmin/db/place2/train_chosen  #place2
resume: #check_celeba_rand
resume_iter: 200000
checkpoints: checkpt_celeb


use_guidance: False
# sn_patchgan, free_patch, orig_patch
discriminator_type: 'free_patch'

generator_type : 'our_parse_fix'
batch_size: 8
#batch_size: 150
#batch_size: 90

# ---------- MASK FROM FILES
mask_type: 'FIX'
fix_mask_path: 'data/box.png' # fix
rand_mask_path: '----'

image_shape: [128, 128, 3]


# training parameters
expname: benchmark_rand
cuda: True
gpu_ids: [0]    # set the GPU ids to use, e.g. [0] or [1, 2]
num_workers: 0
lr: 0.0001
lr_decay: 0.95
momentum: 0.95


weight_decay: 0.0005
beta1: 0.5
beta2: 0.9
niter: 400000
print_iter: 200
#viz_iter: 100
viz_iter: 2000
viz_max_out: 12
snapshot_save_iter: 5000

# loss weight
coarse_l1_alpha: 1.2
l1_loss_alpha: 1.2
ae_loss_alpha: 1.2
pyramid_loss_alpha : 1.0
infer_loss_alpha : 1.2
global_wgan_loss_alpha: 1.
gan_loss_alpha: 0.001
wgan_gp_lambda: 10
attention_alpha: 0.001
percep_alpha: 0.01   # when percep is used


# network parameters
netG:
  input_dim: 5
  ngf: 32

netD:
  input_dim: 3
  ndf: 64
